---
layout: default
title: using_promises.title
next: promise-libraries
prev: errbacks
num: 5
---

<p>{% localize reject_catch.then_reject %}</p>

{% highlight js %}
somePromise.then(function(value) {
  // everything is rainbows
}, function(err) {
  // some terrible thing has happened, and everything is on fire
});
{% endhighlight %}

<p>{% localize reject_catch.handle_reject %}</p>

<p>{% localize reject_catch.making_broken_promise %}</p>

{% highlight js %}
function loadImagePromise(src) {
  var image = new Image();
  var promise = new Promise(function(resolve, reject) {
    image.onload = function() {
      resolve(image);
    };
    image.onerror = function(errorEvent) {
      // it's nice to normalize rejections to be Error instances
      reject(new Error(errorEvent.message));
    };
  });
  image.src = src;
  return promise;
}
{% endhighlight %}

<p>{% localize reject_catch.try_catch_wrapper %}</p>

<p>{% localize reject_catch.simple_chain %}</p>

{% highlight js %}
somePromise
  .then(function(someValue) {
    'This won\'t work'();
  }, function(err) {
    // this will get any error somePromise generates
    // but it will not get the TypeError generated by the resolve handler
  });

somePromise
  .then(function(someValue) {
    'This won\'t work'();
  }, function(err) {
    // some nice handling of an error generated by somePromise
  })
  .catch(function(err) {
    // some nice handling of an error generated by the resolve (or the reject)
    // handler in the above then call.
  });
{% endhighlight %}

<p>{% localize reject_catch.always_handle_errors %}</p>
